Add configurable correlationId name
TouK/cxf-utils pull request #4
Opened 2018-02-19 12:58 UTC by piotrekfus91

Change-Id: I56874ddbd715365ede2e605174c934af43b38b47

2018-02-19 13:13 UTC, michaldabrowski requested changes

2018-02-19 13:13 UTC, michaldabrowski commented on cxf-interceptors/src/test/groovy/pl/touk/cxf/interceptors/CorrelationIdInterceptorTest.groovy
> +
wywal ten enter

2018-02-19 13:13 UTC, michaldabrowski commented on cxf-interceptors/src/main/java/pl/touk/cxf/interceptors/CorrelationIdFeature.java
> +    @Delegate
po co `Delegate`

2018-02-20 11:56 UTC, piotrekfus91 commented on cxf-interceptors/src/test/groovy/pl/touk/cxf/interceptors/CorrelationIdInterceptorTest.groovy
> +
Done

2018-02-20 11:56 UTC, piotrekfus91 commented on cxf-interceptors/src/main/java/pl/touk/cxf/interceptors/CorrelationIdFeature.java
> +    @Delegate
Bo potrzebujemy tego do konfiguracji, jak konfigurujesz feature z XML.

2018-02-20 12:16 UTC, michaldabrowski approved these changes

2018-02-20 12:20 UTC, merged