[#6] Fix not invoking out interceptors during WSDL calls
TouK/cxf-utils pull request #7
Opened 2018-05-11 11:04 UTC by piotrekfus91

Change-Id: I52a20813f61c003d523ba5fcd9fee2a72c87ab7c

2018-05-11 11:14 UTC, michaldabrowski approved these changes

2018-05-11 14:28 UTC, alien11689 commented
@piotrekfus91 Could you add at least one test for your change?

2018-05-11 14:29 UTC, alien11689 requested changes
Could you add at least one test for your change?

2018-05-14 09:51 UTC, alien11689 approved these changes

2018-05-14 09:53 UTC, merged